---
latest_version: 2.41.0
latest_relnote_url: https://raw.github.com/git/git/master/Documentation/RelNotes/2.41.0.txt
latest_release_date: '2023-06-01'
macos_installer:
  url: https://sourceforge.net/projects/git-osx-installer/files/git-2.33.0-intel-universal-mavericks.dmg/download?use_mirror=autoselect
  version: 2.33.0
  release_date: '2021-08-30'
  filename: git-2.33.0-intel-universal-mavericks.dmg
windows_installer:
  portable32:
    filename: PortableGit-2.41.0-32-bit.7z.exe
    release_date: '2023-06-01'
    version: 2.41.0
    url: https://github.com/git-for-windows/git/releases/download/v2.41.0.windows.1/PortableGit-2.41.0-32-bit.7z.exe
  portable64:
    filename: PortableGit-2.41.0-64-bit.7z.exe
    release_date: '2023-06-01'
    version: 2.41.0
    url: https://github.com/git-for-windows/git/releases/download/v2.41.0.windows.1/PortableGit-2.41.0-64-bit.7z.exe
  installer32:
    filename: Git-2.41.0-32-bit.exe
    release_date: '2023-06-01'
    version: 2.41.0
    url: https://github.com/git-for-windows/git/releases/download/v2.41.0.windows.1/Git-2.41.0-32-bit.exe
  installer64:
    filename: Git-2.41.0-64-bit.exe
    release_date: '2023-06-01'
    version: 2.41.0
    url: https://github.com/git-for-windows/git/releases/download/v2.41.0.windows.1/Git-2.41.0-64-bit.exe
plugins:
- jekyll-include-cache
sass:
  sass_dir: _sass
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: about
  values:
    section: about
    title: About - Git
    layout: about
    sidebar: book
- scope:
    path: about
  values:
    section: about
    title: About - Git
    layout: about
    sidebar: book
collections:
  about:
    output: true
    permalink: "/:collection/:name"
  guis:
exclude:
- "*.rb"
