---
latest_version: 2.41.0
latest_relnote_url: https://raw.github.com/git/git/master/Documentation/RelNotes/2.41.0.txt
latest_release_date: '2023-06-01'
plugins:
- jekyll-include-cache
sass:
  sass_dir: _sass
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: about
  values:
    section: about
    title: About - Git
    layout: about
    sidebar: book
- scope:
    path: about
  values:
    section: about
    title: About - Git
    layout: about
    sidebar: book
collections:
  about:
    output: true
    permalink: "/:collection/:name"
  guis:
exclude:
- "*.rb"
