name: Playwright Tests
on:
  push:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to test'
        required: true
        default: 'https://git-scm.com'
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Edit /etc/hosts to map git-scm.com to GitHub
      shell: bash
      run: sudo sh -c 'echo "185.199.108.153 git-scm.com" >>/etc/hosts'
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install @playwright/test
      run: npm install @playwright/test
    - name: Run Playwright tests
      env:
        PLAYWRIGHT_TEST_URL: http://git-scm.com
      run: npx playwright test --project=chrome
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
